### ISSUE TITLE
Comparing two nrl-source values in nrl-eval node

### ISSUE THREAD

**Issue by PKGeorgiev** [nidayand/node-red-contrib-norelite#1]
Currently nrl-eval node allows you to compare one nrl-source value with a constant value.

In some cases it will be useful if you were able to compare two nrl-source values.

In my case I'm controlling a boiler which will be turned ON when the temperature is less than 60 C. The value of 60 C (a.k.a. the setpoint) is hardcoded in the flow. I would like to be able to control the setpoint's value from NodeRED Dashboard for example and compare it with boiler's current temperature. 

This will be very flexible.

**Comment by nidayand** [comment]
Ok, thanks for the idea - I haven't run into that scenario but I'll take a look at it

**Comment by nidayand** [comment]
Ok, I've released a new version - 2.6.0 - with this capability for nrl-eval and nrl-gate. The configuration of the components are already quite heavy and I hope it makes sense. You trigger the selection of the value to compare with entering a blank space in the input box and it will simply change into a select box where all nrl-source nodes will be listed for selection.

**Comment by PKGeorgiev** [comment]
Thanks!

But for some reason in NodeRED > Manage palette norelite is listed as 2.5.0:

![image](https://user-images.githubusercontent.com/9254467/42003215-ff3ef806-7a72-11e8-8aa1-5cea9581efb8.png)

When I try npm update I receive:

![image](https://user-images.githubusercontent.com/9254467/42003234-149e32f2-7a73-11e8-8c07-0f31696a3c0e.png)

What may be the problem?

My nodejs version is v6.14.3.

**Comment by nidayand** [comment]
That is really strange. I will take a look

**Comment by nidayand** [comment]
I've created a patch (but with no real changes) and installed it. Works fine for me

**Comment by nidayand** [comment]
I'm running node 8.9.4 but I've just simple, classic, javascript statements and no new functions

**Comment by PKGeorgiev** [comment]
It seems to be related with npm search out of sync: [Flows.nodered.org lists node’s older version instead of latest](https://discourse.nodered.org/t/flows-nodered-org-lists-nodes-older-version-instead-of-latest/1142/2?u=pkgeorgiev)

I've raised a ticket with npm's support and will write you back when I have an answer.
