### ISSUE TITLE
Not working Node-RED after install

### ISSUE THREAD

**Issue by Allday3D** [nidayand/node-red-contrib-norelite#2]
I have installed this (node-red-contrib-norelite 2.6.1) but my dashboard is not working anymore.
Even the example doesn't want to work.
![nrl_error_1](https://user-images.githubusercontent.com/6654754/46401330-e3296800-c6fc-11e8-93b0-f85f775ec2ee.JPG)
Did I miss something here?

**Comment by nidayand** [comment]
What does the log say?

**Comment by nidayand** [comment]
Closed as no feedback
