### ISSUE TITLE
There is a "TypeError: Cannot read property 'indexOf' of undefined" if the eval-node compares to boolean or null/notnull

### ISSUE THREAD

**Issue by simonkaiser9** [nidayand/node-red-contrib-norelite#3]
eval-nodes using boolean or null comparisons are not evaluating, as no value to compare to can be intitialized, leading to a null reference.

The issues occurs in 2.6.1. I fixed it in my local code base and could make a PR, if you are interested.

**Comment by nidayand** [comment]
Thanks - that would be great!
